# --- CONFIGURATION REDIS PROD ---
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}

# --- SERVICE DE MAILS : CONFIGURATION SERVEUR TRANSACTIONNEL (Brevo, AWS SES, Mailgun...) ---
spring.mail.host=${SMTP_HOST}
spring.mail.port=${SMTP_PORT}
spring.mail.username=${SMTP_USERNAME}
spring.mail.password=${SMTP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true