spring.application.name=xflow-auth-service
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true
spring.devtools.restart.poll-interval=2s
spring.devtools.restart.quiet-period=1s

jpa.hibernate.ddl-auto=validate
jpa.properties.hibernate.default_schema=auth
jpa.properties.hibernate.format_sql=false
jpa.open-in-view=false
jpa.flyway.schemas=auth
jpa.flyway.locations=classpath:db/migration
jpa.flyway.baseline-on-migrate=true

rsa.private-key=${RSA_PRIVATE_KEY}
rsa.public-key=${RSA_PUBLIC_KEY}
rsa.expiration-ms=${EXPIRATION_MS}
jwt.auth.max-failed-attempts: ${AUTH_MAX_FAILED_ATTEMPTS}
jwt.auth.lockout-duration-minutes: ${AUTH_LOCKOUT_DURATION_MINUTES}
jwt.anonymous-token.ttl-hours: ${ANONYMOUS_TOKEN_TTL_HOURS}

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
management.health.db.enabled=true