spring.application.name=xflow-auth-service
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true
spring.devtools.restart.poll-interval=2s
spring.devtools.restart.quiet-period=1s

jpa.hibernate.ddl-auto=validate
jpa.properties.hibernate.default_schema=auth
jpa.properties.hibernate.format_sql=false
jpa.open-in-view=false
jpa.flyway.schemas=auth
jpa.flyway.locations=classpath:db/migration
jpa.flyway.baseline-on-migrate=true