# --- DEVTOOLS (Uniquement utile en Dev) ---
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true
spring.devtools.restart.poll-interval=2s
spring.devtools.restart.quiet-period=1s

# --- CONFIGURATION REDIS LOCAL (Valeurs par défaut si non définies) ---
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}

# --- SERVICE DE MAILS : CONFIGURATION MAILPIT ---
spring.mail.host=mailpit-dev
spring.mail.port=${MAILPIT_SMTP_PORT}
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.username=noreply@xflow.com
