apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: xflow-services
  description: XFlow platform system
spec:
  owner: platform-team
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: xflow-services
  description: Monorepo for XFlow platform services
  annotations:
    backstage.io/techdocs-ref: dir:docs
spec:
  type: website
  lifecycle: experimental
  owner: platform-team
  system: xflow-services
