services:
  postgres:
    image: postgis/postgis:16-3.4
    container_name: postgres
    environment:
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      POSTGRES_DB: ${POSTGRES_DB:-xflow}
      POSTGRES_USER: ${POSTGRES_USER:-xflow}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-xflow}
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    command: >
      postgres
        -c custom.app=${COMPOSE_PROJECT_NAME:-xflow}
        -c custom.db_password=${POSTGRES_PASSWORD:-xflow}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - ./infra/docker/sql:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data
    networks:
      - xflow-network

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "${REDIS_PORT:-6379}:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - xflow-network

  xflow-api-gateway:
    build:
      context: ./services/xflow-api-gateway
    volumes:
      - ~/.m2:/root/.m2
    ports:
      - "${API_GATEWAY_PORT:-8080}:8080"
    command: ["./mvnw", "spring-boot:run"]
    depends_on:
      - xflow-auth-service
    restart: on-failure
    networks:
      - xflow-network

  xflow-auth-service:
    build:
      context: ./services/xflow-auth-service
    volumes:
      - ~/.m2:/root/.m2
    ports:
      - "${AUTH_SERVICE_PORT:-8081}:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/${POSTGRES_DB:-xflow}
      - SPRING_DATASOURCE_USERNAME=auth_${COMPOSE_PROJECT_NAME:-xflow}
      - SPRING_DATASOURCE_PASSWORD=auth_${POSTGRES_PASSWORD:-xflow}
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=org.postgresql.Driver
    command: ["./mvnw", "spring-boot:run"]
    depends_on:
      - postgres
    networks:
      - xflow-network

volumes:
  pgdata:

networks:
  xflow-network: