services:
  postgres:
    container_name: postgres-dev

  redis:
    container_name: redis-dev

  docs:
    container_name: docs-dev
    command: serve -a 0.0.0.0:8000

  mailpit:
    container_name: mailpit-dev
    image: axllent/mailpit
    restart: unless-stopped
    ports:
      - ${MAILPIT_SMTP_PORT:-1025}:1025
      - ${MAILPIT_WEB_UI_PORT:-8025}:8025
    environment:
      - MP_MAX_MESSAGES=5000
      - MP_SMTP_AUTH_ACCEPT_ANY=1
      - MP_SMTP_AUTH_ALLOW_INSECURE=1
    networks:
      - xflow-network

  xflow-api-gateway:
    build:
      target: dev
    container_name: api-gateway-dev
    environment:
      - SPRING_PROFILES_ACTIVE=${ENV:-dev}
      - SPRING_DEVTOOLS_RESTART_ENABLED=true
    volumes:
      - ./pom.xml:/xflow/pom.xml
      - ./services/xflow-api-gateway:/xflow/gateway/app
      - ~/.m2:/root/.m2

  xflow-auth-service:
    build:
      target: dev
    container_name: auth-service-dev
    environment:
      - REDIS_HOST=redis-dev
      - SPRING_PROFILES_ACTIVE=${ENV:-dev}
      - MAILPIT_SMTP_PORT=${MAILPIT_SMTP_PORT:-1025}
    volumes:
      - ./pom.xml:/xflow/pom.xml
      - ./services/xflow-auth-service:/xflow/auth/app
      - ~/.m2:/root/.m2
    depends_on:
      - mailpit

volumes:
  pgdata:
  
networks:
  xflow-network:
    name: ${COMPOSE_PROJECT_NAME:-xflow}-network-dev
    # external: true