spring:
  application:
    name: xflow-api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://xflow-auth-service:8080
          predicates:
            - Path=/auth/**
        - id: auth-users
          uri: http://xflow-auth-service:8080
          predicates:
            - Path=/users/**
        - id: auth-audit-logs
          uri: http://xflow-auth-service:8080
          predicates:
            - Path=/audit-logs/**
        - id: auth-api-docs
          uri: http://xflow-auth-service:8080
          predicates:
            - Path=/auth-service/**, /webjars/**