spring:
  application:
    name: xflow-api-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - PATCH
            allowedHeaders: "*"
      routes:
        - id: auth-service
          uri: http://xflow-auth-service:8080
          predicates:
            - Path=/auth/**
        - id: auth-users
          uri: http://xflow-auth-service:8080
          predicates:
            - Path=/users/**
        - id: auth-audit-logs
          uri: http://xflow-auth-service:8080
          predicates:
            - Path=/audit-logs/**
        - id: auth-api-docs
          uri: http://xflow-auth-service:8080
          predicates:
            - Path=/auth-service/**, /webjars/**, /api/swagger-ui/**, /v3/api-docs/**
          filters:
          - 'RewritePath=/auth-service/(?<segment>.*), /${segment}'