apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: xflow-backstage
  description: XFlow Developer Portal powered by Spotify Backstage
spec:
  type: website
  lifecycle: experimental
  owner: platform-team
  system: xflow-services
